### ISSUE TITLE
Problem with viewModels

### ISSUE THREAD

**Issue by DBFBlackbull** [fatihBulbul/UniqueAttribute#1]
The current version only works if the view depends directly on the domain models used in the database. If each view instead depends on ViewModels, seperated from the domain model, then the database lookup fails as the ViewModel is not part of the db.Set

Take a look at the onion architecture and please try to update your annotation tag to handle viewmodels aswell :)

https://github.com/snebjorn/mvc-onion-template link for onion architecture

**Comment by fatihBulbul** [comment]
Please check again
